name: Mirage
version: '${project.version}'
main: gg.bonka.mirage.Mirage
api-version: '1.20.6'
load: STARTUP
depend: [ProtocolLib]
authors: [Stanley Dam @ Bonka Software]
description: A minecraft plugin that can reset worlds at server startup
website: https://bonka.gg/
